### ISSUE TITLE
SVGs do not render correctly after publish and page reload

### ISSUE THREAD

**Issue by ptrkstr** [b4rtaz/t3mpl-server#1]
Steps:
1. Open up any template in the editor (using `t3mpl-one` for this example)
2. Select a component that requires an image upload
3. Upload an SVG
4. Notice that the SVG displays correctly
5. Publish the page
6. Reload the page
7. Notice that the SVG no longer renders

PNGs work correctly.

See attached video for an example.

https://user-images.githubusercontent.com/11362913/146241539-6c091a1b-8366-4e9b-81fa-2de933d5bce3.mp4

**Comment by b4rtaz** [comment]
I've [fixed it](https://github.com/b4rtaz/t3mpl-server/commit/e67d8adee23b313784fdd5cc3d168e2d91faf6f9). Please upgrade t3mpl-server to 0.4.2.

**Comment by ptrkstr** [comment]
Thank you fixing that so quickly @b4rtaz, it now works perfectly!
This is an incredible project, thank you for building it.
